changelog:
  categories:
    - title: "Breaking Changes 💥"
      labels:
        - "breaking-change"
    - title: "New Features ✨"
      labels:
        - "feature"
    - title: "Bug Fixes 🐛"
      labels:
        - "fix"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "ignore-release"
    authors:
      - "github-actions[bot]"

