changelog:
  categories:
    - title: "Breaking Changes 💥"
      labels:
        - "breaking-change"
        - "major"
    - title: "Features ✨"
      labels:
        - "enhancement"
        - "feature"
        - "feat"
    - title: "Bug Fixes 🐛"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation 📚"
      labels:
        - "documentation"
        - "docs"
    - title: "Maintenance 🧹"
      labels:
        - "chore"
        - "refactor"
        - "ci"
        - "dependencies"
  exclude:
    labels:
      - "skip-changelog"
    authors:
      - "github-actions[bot]"

